{
	"ActionResult": {
		"_Name": "init"
	},
	"ActivityIndicatorText": "Downloading...",
	"DefiningRequests": [
		{
			"Name": "Customers",
			"Query": "Customers"
		},
		{
			"Name": "Products",
			"Query": "Products"
		},
		{
			"Name": "SalesOrderItems",
			"Query": "SalesOrderItems"
		},
		{
			"Name": "SalesOrderHeaders",
			"Query": "SalesOrderHeaders"
		}
	],
	"OnFailure": "/SampleDemoApp/Actions/Service/InitializeOfflineFailureMessage.action",
	"OnSuccess": "/SampleDemoApp/Actions/LogSetState.action",
	"Service": "/SampleDemoApp/Services/SampleServiceV2.service",
	"ShowActivityIndicator": true,
	"_Type": "Action.Type.OfflineOData.Initialize"
}