{
	"Service": "/SampleDemoApp/Services/SampleServiceV2.service",
	"_Type": "Action.Type.OfflineOData.Upload",
	"ActionResult": {
		"_Name": "sync"
	},
	"OnSuccess": "/SampleDemoApp/Actions/Service/DownloadStartedMessage.action",
	"OnFailure": "/SampleDemoApp/Actions/Service/SyncFailureMessage.action"
}